In [18]:
import pandas as pd

In [19]:
filename = 'song_unduplicated.csv'
names = ['albumname','songname','singer','singermid','songmid','tags','tagsid','visitnum','albummid','url']
data = pd.read_csv(filename, names = names, encoding='utf-8')

In [20]:
data.drop([0], inplace = True)
data.reset_index(drop=True)

,albumname,songname,singer,singermid,songmid,tags,tagsid,visitnum,albummid,url
0,2020热曲DJ,带泪的鱼 (DJ版),李小豪,004dJwRH4WEf1p,000Sp3eY1XAIAU,"DJ,开车","14,85",101015449,000hXHcA0fGOM3,https://y.qq.com/n/yqq/song/000Sp3eY1XAIAU.html
1,Insomniac,Ring My Bells,Enrique Iglesias,004SBLbl1aKeWR,002Aa6p30yS1Qc,"R&B,英语,流行","6,167,8",144425847,0043QgUT44uzkH,https://y.qq.com/n/yqq/song/002Aa6p30yS1Qc.html
2,我们不一样,最美情侣 (DJ加快版),范小松,002wHEjm0vvEjs,001um0ns4ICC37,DJ,14,1900395,0039IFLn2imRF9,https://y.qq.com/n/yqq/song/001um0ns4ICC37.html
3,小乒和小乓,小乒和小乓,于文文,000poF8D027tPr,002NMqLN0AhY2T,"国语,流行,校园","165,6,16",6169595,003UGaCn4KkZ8b,https://y.qq.com/n/yqq/song/002NMqLN0AhY2T.html
4,情深往事直到永远,相思比梦长,费玉清,0040MELG3TS8OW,000h8hEG2pmWC2,经典,136,13849849,003O0rxy1z86JW,https://y.qq.com/n/yqq/song/000h8hEG2pmWC2.html
...,...,...,...,...,...,...,...,...,...,...
54199,Finding Neverland,Finding Neverland,Teske,000tSmAP19fOoN,002mZrCW0nKv9h,英语,167,4281553,003XEYPH2csocp,https://y.qq.com/n/yqq/song/002mZrCW0nKv9h.html
54200,追梦,烟火,吴奇隆,004MgTMW0cgf0Z,002mpQ3s0aIV0w,"经典,国语","136,165",78344737,003NAU4t2XJ9Zx,https://y.qq.com/n/yqq/song/002mpQ3s0aIV0w.html
54201,星合,星合,all at once (オール・アット・ワンス),003dhCGr4OczpC,003nXMOp1cfvTB,"日语,ACG","169,39",3395777,0028YSHK3AURvj,https://y.qq.com/n/yqq/song/003nXMOp1cfvTB.html
54202,执念,年少轻狂,齐一,0020IaUo4Vgsjk,004d5c3M3hW2rV,"流行,励志,国语","6,125,165",2016179,004Nyvd8070Fp0,https://y.qq.com/n/yqq/song/004d5c3M3hW2rV.html
54203,原创歌曲合集,杏林无花,"双笙,易言","001t94rh4OpQn0,0027DTPN23aYCZ",004LL2c427sgmo,"古风,治愈","194,116",36719768,000dQblX4Xho6U,https://y.qq.com/n/yqq/song/004LL2c427sgmo.html

In [21]:
df1 = data[['songmid','singermid']]
df1.columns = ['songmid','singermid']
df2 = df1['singermid'].str.split(',', expand = True).stack()
df2 = df2.reset_index(level=1,drop=True)
df2.name = 'singermid'
df_new = df1.drop(['singermid'], axis = 1).join(df2)
df_new.reset_index(drop=True)
df_new.to_csv('song_singer.csv',encoding = 'utf-8', index=False)

In [22]:
df1 = data[['songmid', 'tagsid']]
df1.columns = ['songmid', 'tagsid']
df2 = df1['tagsid'].str.split(',', expand = True).stack()
df2 = df2.reset_index(level=1,drop=True)
df2.name = 'tagsid'
df_new = df1.drop(['tagsid'], axis = 1).join(df2)
df_new.reset_index(drop=True)
df_new.to_csv('song_tag.csv',encoding = 'utf-8', index=False)

In [23]:
df1 = data[['songmid','albummid']]
df1.columns = ['songmid','albummid']
df1.to_csv('song_album.csv',encoding = 'utf-8', index=False)

In [26]:
df = pd.read_csv('song_album.csv',encoding='utf-8')
df

              songmid        albummid
0      000Sp3eY1XAIAU  000hXHcA0fGOM3
1      002Aa6p30yS1Qc  0043QgUT44uzkH
2      001um0ns4ICC37  0039IFLn2imRF9
3      002NMqLN0AhY2T  003UGaCn4KkZ8b
4      000h8hEG2pmWC2  003O0rxy1z86JW
...               ...             ...
54199  002mZrCW0nKv9h  003XEYPH2csocp
54200  002mpQ3s0aIV0w  003NAU4t2XJ9Zx
54201  003nXMOp1cfvTB  0028YSHK3AURvj
54202  004d5c3M3hW2rV  004Nyvd8070Fp0
54203  004LL2c427sgmo  000dQblX4Xho6U

[54204 rows x 2 columns]

In [27]:
df.dropna(axis=0, how='any', inplace=True)
df

              songmid        albummid
0      000Sp3eY1XAIAU  000hXHcA0fGOM3
1      002Aa6p30yS1Qc  0043QgUT44uzkH
2      001um0ns4ICC37  0039IFLn2imRF9
3      002NMqLN0AhY2T  003UGaCn4KkZ8b
4      000h8hEG2pmWC2  003O0rxy1z86JW
...               ...             ...
54199  002mZrCW0nKv9h  003XEYPH2csocp
54200  002mpQ3s0aIV0w  003NAU4t2XJ9Zx
54201  003nXMOp1cfvTB  0028YSHK3AURvj
54202  004d5c3M3hW2rV  004Nyvd8070Fp0
54203  004LL2c427sgmo  000dQblX4Xho6U

[54204 rows x 2 columns]

In [23]:
df.to_csv('album.csv')

In [ ]:
df = data[['singermid','singer']]
df.column = ['singermid','singer']
df.drop(['singermid'])